// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofvwripyhjnslvfvvmnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdndyaXB5aGpuc2x2ZnZ2bW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjE0MjcsImV4cCI6MjA3NDY5NzQyN30.82yWKRq-aJ1jlLpE6frPa9OTb7U4MXM0jDKz-eVxIFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});